defaults:
  - submitit_slurm

timeout_min: 60
gpus_per_node: 1
tasks_per_node: 1
gres: "gpu:${hydra.launcher.gpus_per_node}"
qos: qos_gpu-dev
cpus_per_gpu: 10
gpus_per_task: ${hydra.launcher.gpus_per_node}
additional_parameters:
  account: ${project_id}@gpu
  distribution: "block:block"
  hint: nomultithread
  time: "${hours}:00:00"
setup:
  - "#SBATCH -C v100-32g"
  - "export WANDB_MODE=offline"